pipeline {
  agent any

  stages {
    stage('Install requirements') {
      steps {
        sh 'pip install -r requirements.txt'
      }
    }
    stage('Run tests') {
      steps {
        sh 'pytest tests/'
      }
    }
    stage('Train Model') {
      steps {
        sh 'python src/train.py'
      }
    }
  }
}
